name: Build & Push OpenSpoolman

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          echo "----"
          find . -maxdepth 3 -type f -iname 'Dockerfile' -print || true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./openspoolman-main
          file: ./openspoolman-main/Dockerfile   # exakt so groß/klein geschrieben!
          platforms: linux/amd64,linux/arm64
          push: true
          tags: utir/openspoolman:latest
